'%sylius.model.order.class%':
     itemOperations:
            shop_add_item:
                method: POST
                path: /shop/orders/{tokenValue}/items
                messenger: input
                input: Setono\SyliusGiftCardPlugin\Api\Command\AddItemToCart
                normalization_context:
                    groups: ['shop:cart:read']
                denormalization_context:
                    groups: ['shop:cart:add_item']
                openapi_context:
                    summary: 'Adds Item to cart'
